/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { Account } from "./account";
import type { Contact } from "./contact";
import type { Deal } from "./deal";

export type AccountDetail = Account & {
  contacts: Contact[];
  deals: Deal[];
};
