/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface AccountInput {
  /** @minLength 1 */
  name: string;
  industry?: string | null;
  website?: string | null;
  phone?: string | null;
  owner?: string | null;
  size?: string | null;
  location?: string | null;
  notes?: string | null;
}
