/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomPropertyValuesMap } from "./customPropertyValuesMap";

export interface Account {
  id: string;
  name: string;
  industry?: string | null;
  website?: string | null;
  phone?: string | null;
  owner?: string | null;
  size?: string | null;
  location?: string | null;
  notes?: string | null;
  createdAt: Date;
  updatedAt: Date;
  openDealValue: number;
  openDealCount: number;
  contactCount: number;
  customProperties?: CustomPropertyValuesMap;
}
