/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityType } from "./activityType";

export interface Activity {
  id: string;
  type: ActivityType;
  subject: string;
  body?: string | null;
  occurredAt: Date;
  dueAt?: Date | null;
  reminderSentAt?: Date | null;
  completedAt?: Date | null;
  owner?: string | null;
  ownerId?: string | null;
  ownerName?: string | null;
  ownerAvatarUrl?: string | null;
  dealId?: string | null;
  dealName?: string | null;
  leadId?: string | null;
  leadName?: string | null;
  contactId?: string | null;
  contactName?: string | null;
  accountId?: string | null;
  accountName?: string | null;
  createdAt: Date;
}
