/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityType } from "./activityType";

export interface ActivityInput {
  type: ActivityType;
  /** @minLength 1 */
  subject: string;
  body?: string | null;
  occurredAt: Date;
  dueAt?: Date | null;
  owner?: string | null;
  ownerId?: string | null;
  dealId?: string | null;
  leadId?: string | null;
  contactId?: string | null;
  accountId?: string | null;
}
