/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentResult } from "./assessmentResult";

export interface Assessment {
  id: string;
  dealId: string;
  dealName?: string | null;
  accountName?: string | null;
  gradeApplying?: string | null;
  studentLocation?: string | null;
  isSibling: boolean;
  /**
   * @minimum 0
   * @maximum 100
   */
  englishScore?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  mathScore?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  scienceScore?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  interviewScore?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  testEnglishScore?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  testMathScore?: number | null;
  result: AssessmentResult;
  notes?: string | null;
  assessedAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}
