/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthUser } from "./authUser";

export interface AuthUserEnvelope {
  /** The Replit user attached to the current session, if any. Always returned when a session exists, even if the user is not on the staff allow-list — the UI uses this to show a "not authorised" page that names the email they signed in with. */
  user: AuthUser | null;
  /** Whether the signed-in user is on the `ALLOWED_EMAILS` allow-list and may access admissions data. False when no user is signed in. */
  isAuthorized: boolean;
  /** Whether the signed-in user is an admin (listed in `ADMIN_EMAILS`, or — if that env var is unset — any allow-listed staffer). Admins can moderate other users' content such as editing or deleting any note. */
  isAdmin: boolean;
}
