/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface AvailabilitySettings {
  userId: string;
  slug: string;
  /** Days of week (0=Sunday … 6=Saturday) the staff is bookable. */
  weekdays: number[];
  /**
   * @minimum 0
   * @maximum 1440
   */
  startMinute: number;
  /**
   * @minimum 0
   * @maximum 1440
   */
  endMinute: number;
  /**
   * @minimum 5
   * @maximum 480
   */
  durationMinutes: number;
  /**
   * @minimum 0
   * @maximum 240
   */
  bufferMinutes: number;
  timezone: string;
  enabled: boolean;
  ownerName?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
