/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface AvailabilityInput {
  /** @maxLength 60 */
  slug?: string | null;
  weekdays: number[];
  /**
   * @minimum 0
   * @maximum 1440
   */
  startMinute: number;
  /**
   * @minimum 0
   * @maximum 1440
   */
  endMinute: number;
  /**
   * @minimum 5
   * @maximum 480
   */
  durationMinutes: number;
  /**
   * @minimum 0
   * @maximum 240
   */
  bufferMinutes: number;
  /** @minLength 1 */
  timezone: string;
  enabled: boolean;
}
