/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface Booking {
  id: string;
  slotAt: Date;
  durationMinutes: number;
  parentName: string;
  parentEmail: string;
  parentPhone?: string | null;
  childName: string;
  grade?: string | null;
  notes?: string | null;
  status: string;
  leadId?: string | null;
  activityId?: string | null;
  calendarEventId?: string | null;
  createdAt: Date;
}
