/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-user calendar subscription token + ready-to-paste URL.
 */
export interface CalendarSubscription {
  hasToken: boolean;
  /** @nullable */
  token?: string | null;
  /**
   * Absolute URL the calendar app should subscribe to. Includes the token query parameter.
   * @nullable
   */
  feedUrl?: string | null;
  /** @nullable */
  createdAt?: Date | null;
}
