/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A row of CSV data being imported as a contact. All fields are optional strings; the server validates and coerces them.
 */
export interface ContactImportRow {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  title?: string;
  accountName?: string;
  notes?: string;
}
