/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomPropertyValuesMap } from "./customPropertyValuesMap";
import type { LifecycleStage } from "./lifecycleStage";

export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  email?: string | null;
  phone?: string | null;
  title?: string | null;
  accountId?: string | null;
  accountName?: string | null;
  notes?: string | null;
  lifecycleStage: LifecycleStage;
  createdAt: Date;
  updatedAt: Date;
  customProperties?: CustomPropertyValuesMap;
}
