/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface ConvertLeadInput {
  /** @minLength 1 */
  dealName: string;
  value: number;
  expectedCloseDate?: Date | null;
  accountName?: string | null;
  accountId?: string | null;
}
