/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateUserInput {
  /**
   * Staff member's display name (first + last as a single string is fine).
   * @minLength 1
   */
  name: string;
  /**
   * Optional role/title (e.g. 'Admissions Supervisor'). Stored alongside the name so it shows in owner pickers.
   * @nullable
   */
  role?: string | null;
  /**
   * Optional email. Required if you want to receive task reminders for this user.
   * @nullable
   */
  email?: string | null;
}
