/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { CsvImportError } from "./csvImportError";

export interface CsvImportReport {
  totalRows: number;
  validRows: number;
  insertedRows: number;
  /** Rows whose key (e.g. account name) already matched a record in the database and were skipped instead of being re-inserted. Always present; 0 when the importer does not dedupe. */
  existingRows: number;
  errorRows: number;
  dryRun: boolean;
  errors: CsvImportError[];
}
