/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface CsvImportError {
  /** 1-based row number within the data rows (excluding header) */
  rowNumber: number;
  field?: string | null;
  message: string;
}
