/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { CsvImportError } from "./csvImportError";

/**
 * A single audited CSV import — who ran it, how many rows landed, and any row-level errors.
 */
export interface CsvImportRecord {
  id: string;
  /** Which collection was imported (e.g. "leads", "contacts"). */
  entity: string;
  importedAt: Date;
  /** Display name of the user who ran the import. */
  importedBy?: string | null;
  importedById?: string | null;
  totalRows: number;
  validRows: number;
  insertedRows: number;
  errorRows: number;
  errors: CsvImportError[];
}
