/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomPropertyRecordType } from "./customPropertyRecordType";
import type { CustomPropertyType } from "./customPropertyType";

export interface CustomProperty {
  id: string;
  recordType: CustomPropertyRecordType;
  key: string;
  name: string;
  type: CustomPropertyType;
  required: boolean;
  options?: string[] | null;
  displayOrder: number;
  createdAt: Date;
  updatedAt: Date;
}
