/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type CustomPropertyRecordType =
  (typeof CustomPropertyRecordType)[keyof typeof CustomPropertyRecordType];

export const CustomPropertyRecordType = {
  lead: "lead",
  deal: "deal",
  account: "account",
  contact: "contact",
} as const;
