/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type DealStage = (typeof DealStage)[keyof typeof DealStage];

export const DealStage = {
  open_lead: "open_lead",
  report_card_review: "report_card_review",
  assessment: "assessment",
  offer: "offer",
  enrolled: "enrolled",
  declined: "declined",
} as const;
