/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A row of CSV data being imported as a deal/application. All fields are optional strings; the server validates and coerces them. accountName is matched case-insensitively to existing accounts; stage is validated against the DealStage enum. primaryContactEmail is matched case-insensitively to an existing contact's email; primaryContactName ("First Last") is matched case-insensitively against contacts on the resolved account. Either contact column is optional, but when provided the value must resolve to an existing contact.
 */
export interface DealImportRow {
  name?: string;
  stage?: string;
  accountName?: string;
  primaryContactEmail?: string;
  primaryContactName?: string;
  owner?: string;
  value?: string;
  expectedClose?: string;
  gradeApplying?: string;
  studentLocation?: string;
  isSibling?: string;
  notes?: string;
}
