/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { DealStage } from "./dealStage";

export interface DealInput {
  /** @minLength 1 */
  name: string;
  stage: DealStage;
  /** @minimum 0 */
  value: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  probability: number;
  expectedCloseDate?: Date | null;
  accountId?: string | null;
  primaryContactId?: string | null;
  owner?: string | null;
  ownerId?: string | null;
  notes?: string | null;
  gradeApplying?: string | null;
  studentLocation?: string;
  isSibling?: boolean;
}
