/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { EligibilityLocation } from "./eligibilityLocation";
import type { EligibilityTargetGrade } from "./eligibilityTargetGrade";

export interface EligibilityCheckInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  studentName: string;
  targetGrade: EligibilityTargetGrade;
  location: EligibilityLocation;
  /** @minLength 1 */
  fileObjectPath: string;
  /** @minLength 1 */
  fileMimeType: string;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  dealId?: string | null;
}
