/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type EligibilityLocation =
  (typeof EligibilityLocation)[keyof typeof EligibilityLocation];

export const EligibilityLocation = {
  dubai: "dubai",
  non_dubai: "non_dubai",
} as const;
