/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { EligibilitySubjectMark } from "./eligibilitySubjectMark";

export interface EligibilityExtractedMarks {
  subjects?: EligibilitySubjectMark[];
  /**
   * Aggregate % across all subjects, if reported.
   * @nullable
   */
  aggregatePercentage?: number | null;
  /** @nullable */
  notes?: string | null;
}
