/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type EligibilityTargetGrade =
  (typeof EligibilityTargetGrade)[keyof typeof EligibilityTargetGrade];

export const EligibilityTargetGrade = {
  NUMBER_2: "2",
  NUMBER_3: "3",
  NUMBER_4: "4",
  NUMBER_5: "5",
  NUMBER_6: "6",
  NUMBER_7: "7",
  NUMBER_8: "8",
  NUMBER_9: "9",
  NUMBER_10: "10",
  NUMBER_11: "11",
  NUMBER_12: "12",
} as const;
