/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { EligibilityExtractedMarks } from "./eligibilityExtractedMarks";
import type { EligibilityLocation } from "./eligibilityLocation";
import type { EligibilityTargetGrade } from "./eligibilityTargetGrade";
import type { EligibilityVerdict } from "./eligibilityVerdict";

export interface EligibilityCheck {
  id: string;
  /** @nullable */
  dealId?: string | null;
  studentName: string;
  targetGrade: EligibilityTargetGrade;
  location: EligibilityLocation;
  fileObjectPath: string;
  fileMimeType: string;
  /** @nullable */
  fileName?: string | null;
  extractedMarks?: EligibilityExtractedMarks | null;
  verdict: EligibilityVerdict;
  reasoning: string;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  createdByName?: string | null;
  createdAt: Date;
}
