/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type EligibilityVerdict =
  (typeof EligibilityVerdict)[keyof typeof EligibilityVerdict];

export const EligibilityVerdict = {
  eligible: "eligible",
  not_eligible: "not_eligible",
  needs_review: "needs_review",
} as const;
