/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * How the email is delivered. `gmail` requires the Gmail connector to be authorized for this workspace.
 */
export type EmailSendInputTransport =
  (typeof EmailSendInputTransport)[keyof typeof EmailSendInputTransport];

export const EmailSendInputTransport = {
  gmail: "gmail",
  mailto: "mailto",
} as const;
