/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { Activity } from "./activity";
import type { EmailSendOutputTransport } from "./emailSendOutputTransport";

export interface EmailSendOutput {
  activity: Activity;
  transport: EmailSendOutputTransport;
  /** Gmail-assigned message id when transport=gmail. */
  gmailMessageId?: string | null;
}
