/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
  bodyHtml: string;
  createdById?: string | null;
  createdByName?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
