/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface EmailRenderOutput {
  subject: string;
  bodyHtml: string;
  /** Best-guess recipient email derived from the contact or lead. */
  to?: string | null;
  /** Merge tags that could not be resolved (rendered as empty strings). */
  unresolvedTags: string[];
}
