/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { EmailSendInputTransport } from "./emailSendInputTransport";

export interface EmailSendInput {
  /** @minLength 1 */
  to: string;
  /** @minLength 1 */
  subject: string;
  /** @minLength 1 */
  bodyHtml: string;
  templateId?: string | null;
  leadId?: string | null;
  contactId?: string | null;
  dealId?: string | null;
  accountId?: string | null;
  /** How the email is delivered. `gmail` requires the Gmail connector to be authorized for this workspace. */
  transport?: EmailSendInputTransport;
}
