/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Provide whatever record IDs are in scope. Merge tags referencing
unresolved fields (e.g. `{{deal.stage}}` with no dealId) are left
blank in the rendered output.

 */
export interface EmailRenderInput {
  leadId?: string | null;
  contactId?: string | null;
  dealId?: string | null;
  accountId?: string | null;
}
