/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type GetCalendarFeedParams = {
  /**
   * @minLength 1
   */
  token: string;
};
