/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { InboxMessageDirection } from "./inboxMessageDirection";

export interface InboxMessage {
  id: string;
  direction: InboxMessageDirection;
  /** @nullable */
  fromEmail?: string | null;
  /** @nullable */
  fromName?: string | null;
  /** @nullable */
  toEmails?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  snippet?: string | null;
  /** @nullable */
  bodyHtml?: string | null;
  /** @nullable */
  bodyText?: string | null;
  /** @nullable */
  sentAt: Date | null;
}
