/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type InboxThreadSummaryStatus =
  (typeof InboxThreadSummaryStatus)[keyof typeof InboxThreadSummaryStatus];

export const InboxThreadSummaryStatus = {
  open: "open",
  closed: "closed",
} as const;
