/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { InboxThreadSummaryStatus } from "./inboxThreadSummaryStatus";

export interface InboxThreadSummary {
  id: string;
  /** @nullable */
  subject: string | null;
  /** @nullable */
  lastMessageAt: Date | null;
  /** @nullable */
  lastSnippet: string | null;
  /** @nullable */
  lastFromName: string | null;
  /** @nullable */
  lastFromEmail?: string | null;
  unreadCount: number;
  status: InboxThreadSummaryStatus;
  /** @nullable */
  contactId: string | null;
  /** @nullable */
  contactName: string | null;
  /** @nullable */
  assigneeId?: string | null;
  /** @nullable */
  assigneeName?: string | null;
}
