/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type InboxMessageDirection =
  (typeof InboxMessageDirection)[keyof typeof InboxMessageDirection];

export const InboxMessageDirection = {
  inbound: "inbound",
  outbound: "outbound",
} as const;
