/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface InboxReplyInput {
  /**
   * HTML body for the reply. Subject is auto-derived from the thread.
   * @minLength 1
   */
  bodyHtml: string;
}
