/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type LeadSource = (typeof LeadSource)[keyof typeof LeadSource];

export const LeadSource = {
  website: "website",
  referral: "referral",
  cold_outreach: "cold_outreach",
  event: "event",
  partner: "partner",
  other: "other",
} as const;
