/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-rule contribution counts behind a lead's current score.
 */
export interface LeadScoreBreakdown {
  emailReplies: number;
  callsAnswered: number;
  meetingsAttended: number;
  assessmentsBooked: number;
  /** Days since the most recent activity (or lead creation). */
  decayDays: number;
  /** Pre-cap score (positive contributions minus decay). */
  raw: number;
  /** Final score after the 0-100 cap. */
  capped: number;
}
