/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Score band derived from `score` (cold <30, warm 30-69, hot >=70).
 */
export type LeadBand = (typeof LeadBand)[keyof typeof LeadBand];

export const LeadBand = {
  cold: "cold",
  warm: "warm",
  hot: "hot",
} as const;
