/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A row of CSV data being imported as a lead. All fields are optional strings; the server validates and coerces them.
 */
export interface LeadImportRow {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  company?: string;
  title?: string;
  status?: string;
  source?: string;
  owner?: string;
  estimatedValue?: string;
  notes?: string;
}
