/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { CustomPropertyValuesMap } from "./customPropertyValuesMap";
import type { LeadBand } from "./leadBand";
import type { LeadScoreBreakdown } from "./leadScoreBreakdown";
import type { LeadSource } from "./leadSource";
import type { LeadStatus } from "./leadStatus";

export interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  title?: string | null;
  status: LeadStatus;
  source: LeadSource;
  owner?: string | null;
  ownerId?: string | null;
  ownerName?: string | null;
  ownerAvatarUrl?: string | null;
  estimatedValue?: number | null;
  notes?: string | null;
  /**
   * Engagement score 0-100 maintained by the lead-scoring engine.
   * @minimum 0
   * @maximum 100
   */
  score: number;
  /** Score band derived from `score` (cold <30, warm 30-69, hot >=70). */
  band: LeadBand;
  scoreUpdatedAt: Date;
  scoreBreakdown?: LeadScoreBreakdown;
  createdAt: Date;
  updatedAt: Date;
  customProperties?: CustomPropertyValuesMap;
}
