/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { LeadSource } from "./leadSource";
import type { LeadStatus } from "./leadStatus";

export interface LeadInput {
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  title?: string | null;
  status: LeadStatus;
  source: LeadSource;
  owner?: string | null;
  ownerId?: string | null;
  estimatedValue?: number | null;
  notes?: string | null;
}
