/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single distinct legacy `owner` text value with how many leads/deals/activities still need a real owner.
 */
export interface LegacyOwnerSummary {
  legacyOwner: string;
  leadCount: number;
  dealCount: number;
  activityCount: number;
  totalCount: number;
}
