/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type LifecycleStage =
  (typeof LifecycleStage)[keyof typeof LifecycleStage];

export const LifecycleStage = {
  lead: "lead",
  mql: "mql",
  sql: "sql",
  opportunity: "opportunity",
  customer: "customer",
  other: "other",
} as const;
