/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { LifecycleStage } from "./lifecycleStage";

export interface LifecycleFunnelEntry {
  stage: LifecycleStage;
  count: number;
  reachedCount: number;
  conversionPct: number;
}
