/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { ListInboxThreadsStatus } from "./listInboxThreadsStatus";

export type ListInboxThreadsParams = {
  /**
 * "unread" — open threads with at least one unread inbound message;
"open" (default) — open threads matched to a contact;
"closed" — closed threads;
"unmatched" — threads with no contact match yet;
"all" — every thread.

 */
  status?: ListInboxThreadsStatus;
  /**
 * Filter by assignee. "me" — threads assigned to the current user;
"unassigned" — threads with no assignee; "any" (default) —
no owner filter; any other value is treated as a user id.

 */
  owner?: string;
};
