/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type ListActivitiesParams = {
  dealId?: string;
  leadId?: string;
  contactId?: string;
  accountId?: string;
  ownerId?: string;
  mine?: boolean;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
