/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type ListImportsParams = {
  /**
   * Optional filter by entity (e.g. "leads", "contacts").
   */
  entity?: string;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
