/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { LeadStatus } from "./leadStatus";
import type { ListLeadsSort } from "./listLeadsSort";

export type ListLeadsParams = {
  search?: string;
  status?: LeadStatus;
  source?: string;
  ownerId?: string;
  mine?: boolean;
  /**
   * Only return leads whose score is >= this value (0-100).
   * @minimum 0
   * @maximum 100
   */
  minScore?: number;
  /**
   * Shortcut for the Hot band threshold (score >= 70).
   */
  hot?: boolean;
  /**
 * Sort order. `score` sorts highest score first; default is most
recently created.

 */
  sort?: ListLeadsSort;
};
