/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type ListInboxThreadsStatus =
  (typeof ListInboxThreadsStatus)[keyof typeof ListInboxThreadsStatus];

export const ListInboxThreadsStatus = {
  unread: "unread",
  open: "open",
  closed: "closed",
  unmatched: "unmatched",
  all: "all",
} as const;
