/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type ListLeadsSort = (typeof ListLeadsSort)[keyof typeof ListLeadsSort];

export const ListLeadsSort = {
  created: "created",
  score: "score",
} as const;
