/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { NoteRecordType } from "./noteRecordType";

export interface Note {
  id: string;
  recordType: NoteRecordType;
  recordId: string;
  body: string;
  isPinned: boolean;
  authorId?: string | null;
  authorName?: string | null;
  authorAvatarUrl?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
