/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface NoteUpdateInput {
  /**
   * @minLength 1
   * @maxLength 50000
   */
  body: string;
}
