/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type NoteRecordType =
  (typeof NoteRecordType)[keyof typeof NoteRecordType];

export const NoteRecordType = {
  lead: "lead",
  deal: "deal",
  account: "account",
  contact: "contact",
} as const;
