/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface PublicBookingInput {
  slotAt: Date;
  /**
   * @minLength 1
   * @maxLength 200
   */
  parentName: string;
  /**
   * @minLength 3
   * @maxLength 200
   */
  parentEmail: string;
  /** @maxLength 50 */
  parentPhone?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  childName: string;
  /** @maxLength 50 */
  grade?: string | null;
  /** @maxLength 2000 */
  notes?: string | null;
}
