/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface PublicBookingResult {
  id: string;
  slotAt: Date;
  durationMinutes: number;
  parentName: string;
  parentEmail: string;
  childName: string;
  grade?: string | null;
  status: string;
  calendarEventId?: string | null;
  staffName: string;
}
