/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportRunRow } from "./reportRunRow";

export interface ReportRunResult {
  rows: ReportRunRow[];
  measureLabel: string;
  dimensionLabel: string;
}
