/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

/**
 * count — row count;
sum_value / avg_value — sum / average of the numeric value column
(deals only); avg_age_days — average age in days from createdAt to now.

 */
export type ReportMeasure = (typeof ReportMeasure)[keyof typeof ReportMeasure];

export const ReportMeasure = {
  count: "count",
  sum_value: "sum_value",
  avg_value: "avg_value",
  avg_age_days: "avg_age_days",
} as const;
