/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type ReportDimension =
  (typeof ReportDimension)[keyof typeof ReportDimension];

export const ReportDimension = {
  owner: "owner",
  source: "source",
  stage: "stage",
  status: "status",
  type: "type",
  month_created: "month_created",
  week_created: "week_created",
  month_closed: "month_closed",
} as const;
