/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportDimension } from "./reportDimension";
import type { ReportMeasure } from "./reportMeasure";
import type { ReportSource } from "./reportSource";

export interface ReportConfig {
  source: ReportSource;
  measure: ReportMeasure;
  dimension: ReportDimension;
}
