/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { ReportChartType } from "./reportChartType";
import type { ReportConfig } from "./reportConfig";
import type { ReportSource } from "./reportSource";

export interface SavedReportInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** @nullable */
  description?: string | null;
  source: ReportSource;
  chartType: ReportChartType;
  config: ReportConfig;
}
