/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type SequenceEnrolmentStatus =
  (typeof SequenceEnrolmentStatus)[keyof typeof SequenceEnrolmentStatus];

export const SequenceEnrolmentStatus = {
  active: "active",
  paused: "paused",
  completed: "completed",
  unenrolled: "unenrolled",
} as const;
