/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface SequenceSummary {
  id: string;
  name: string;
  description?: string | null;
  isActive: boolean;
  stepCount: number;
  activeEnrolments: number;
  createdById?: string | null;
  createdByName?: string | null;
  createdAt: Date;
  updatedAt: Date;
}
