/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { SequenceEnrolmentStatus } from "./sequenceEnrolmentStatus";

export interface SequenceEnrolment {
  id: string;
  sequenceId: string;
  sequenceName: string;
  leadId?: string | null;
  contactId?: string | null;
  status: SequenceEnrolmentStatus;
  currentStep: number;
  stepCount: number;
  nextSendAt?: Date | null;
  lastSentAt?: Date | null;
  pauseReason?: string | null;
  enrolledById?: string | null;
  enrolledByName?: string | null;
  enrolledAt: Date;
  completedAt?: Date | null;
}
