/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { SequenceStepInput } from "./sequenceStepInput";

export interface SequenceInput {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** @maxLength 1000 */
  description?: string | null;
  isActive?: boolean;
  /**
   * @minItems 1
   * @maxItems 50
   */
  steps: SequenceStepInput[];
}
