/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { Activity } from "./activity";
import type { Note } from "./note";
import type { TimelineEntryKind } from "./timelineEntryKind";
import type { TimelineStageChange } from "./timelineStageChange";

/**
 * A single entry in a record's unified timeline. Exactly one of `activity`, `note`, or `stageChange` is populated based on `kind`.
 */
export interface TimelineEntry {
  id: string;
  kind: TimelineEntryKind;
  occurredAt: Date;
  activity?: Activity | null;
  note?: Note | null;
  stageChange?: TimelineStageChange | null;
}
