/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Pipeline CRM API
 * OpenAPI spec version: 0.1.0
 */

export type TimelineEntryKind =
  (typeof TimelineEntryKind)[keyof typeof TimelineEntryKind];

export const TimelineEntryKind = {
  activity: "activity",
  note: "note",
  stage_change: "stage_change",
} as const;
